// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$6 {

    static final FunctionDescriptor sctp_freepaddrs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sctp_freepaddrs$MH = RuntimeHelper.downcallHandle(
        "sctp_freepaddrs",
        constants$6.sctp_freepaddrs$FUNC, false
    );
    static final FunctionDescriptor sctp_getladdrs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sctp_getladdrs$MH = RuntimeHelper.downcallHandle(
        "sctp_getladdrs",
        constants$6.sctp_getladdrs$FUNC, false
    );
    static final FunctionDescriptor sctp_freeladdrs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sctp_freeladdrs$MH = RuntimeHelper.downcallHandle(
        "sctp_freeladdrs",
        constants$6.sctp_freeladdrs$FUNC, false
    );
    static final FunctionDescriptor sctp_sendmsg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle sctp_sendmsg$MH = RuntimeHelper.downcallHandle(
        "sctp_sendmsg",
        constants$6.sctp_sendmsg$FUNC, false
    );
    static final FunctionDescriptor sctp_send$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle sctp_send$MH = RuntimeHelper.downcallHandle(
        "sctp_send",
        constants$6.sctp_send$FUNC, false
    );
    static final FunctionDescriptor sctp_recvmsg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sctp_recvmsg$MH = RuntimeHelper.downcallHandle(
        "sctp_recvmsg",
        constants$6.sctp_recvmsg$FUNC, false
    );
}


