// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_stream_change_event {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("strchange_type"),
        Constants$root.C_SHORT$LAYOUT.withName("strchange_flags"),
        Constants$root.C_INT$LAYOUT.withName("strchange_length"),
        Constants$root.C_INT$LAYOUT.withName("strchange_assoc_id"),
        Constants$root.C_SHORT$LAYOUT.withName("strchange_instrms"),
        Constants$root.C_SHORT$LAYOUT.withName("strchange_outstrms")
    ).withName("sctp_stream_change_event");
    public static MemoryLayout $LAYOUT() {
        return sctp_stream_change_event.$struct$LAYOUT;
    }
    static final VarHandle strchange_type$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("strchange_type"));
    public static VarHandle strchange_type$VH() {
        return sctp_stream_change_event.strchange_type$VH;
    }
    public static short strchange_type$get(MemorySegment seg) {
        return (short)sctp_stream_change_event.strchange_type$VH.get(seg);
    }
    public static void strchange_type$set( MemorySegment seg, short x) {
        sctp_stream_change_event.strchange_type$VH.set(seg, x);
    }
    public static short strchange_type$get(MemorySegment seg, long index) {
        return (short)sctp_stream_change_event.strchange_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strchange_type$set(MemorySegment seg, long index, short x) {
        sctp_stream_change_event.strchange_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strchange_flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("strchange_flags"));
    public static VarHandle strchange_flags$VH() {
        return sctp_stream_change_event.strchange_flags$VH;
    }
    public static short strchange_flags$get(MemorySegment seg) {
        return (short)sctp_stream_change_event.strchange_flags$VH.get(seg);
    }
    public static void strchange_flags$set( MemorySegment seg, short x) {
        sctp_stream_change_event.strchange_flags$VH.set(seg, x);
    }
    public static short strchange_flags$get(MemorySegment seg, long index) {
        return (short)sctp_stream_change_event.strchange_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strchange_flags$set(MemorySegment seg, long index, short x) {
        sctp_stream_change_event.strchange_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strchange_length$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("strchange_length"));
    public static VarHandle strchange_length$VH() {
        return sctp_stream_change_event.strchange_length$VH;
    }
    public static int strchange_length$get(MemorySegment seg) {
        return (int)sctp_stream_change_event.strchange_length$VH.get(seg);
    }
    public static void strchange_length$set( MemorySegment seg, int x) {
        sctp_stream_change_event.strchange_length$VH.set(seg, x);
    }
    public static int strchange_length$get(MemorySegment seg, long index) {
        return (int)sctp_stream_change_event.strchange_length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strchange_length$set(MemorySegment seg, long index, int x) {
        sctp_stream_change_event.strchange_length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strchange_assoc_id$VH = $struct$LAYOUT.varHandle(
            PathElement.groupElement("strchange_assoc_id"));
    public static VarHandle strchange_assoc_id$VH() {
        return sctp_stream_change_event.strchange_assoc_id$VH;
    }
    public static int strchange_assoc_id$get(MemorySegment seg) {
        return (int)sctp_stream_change_event.strchange_assoc_id$VH.get(seg);
    }
    public static void strchange_assoc_id$set( MemorySegment seg, int x) {
        sctp_stream_change_event.strchange_assoc_id$VH.set(seg, x);
    }
    public static int strchange_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_stream_change_event.strchange_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strchange_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_stream_change_event.strchange_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strchange_instrms$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("strchange_instrms"));
    public static VarHandle strchange_instrms$VH() {
        return sctp_stream_change_event.strchange_instrms$VH;
    }
    public static short strchange_instrms$get(MemorySegment seg) {
        return (short)sctp_stream_change_event.strchange_instrms$VH.get(seg);
    }
    public static void strchange_instrms$set( MemorySegment seg, short x) {
        sctp_stream_change_event.strchange_instrms$VH.set(seg, x);
    }
    public static short strchange_instrms$get(MemorySegment seg, long index) {
        return (short)sctp_stream_change_event.strchange_instrms$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strchange_instrms$set(MemorySegment seg, long index, short x) {
        sctp_stream_change_event.strchange_instrms$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strchange_outstrms$VH = $struct$LAYOUT.varHandle(
            PathElement.groupElement("strchange_outstrms"));
    public static VarHandle strchange_outstrms$VH() {
        return sctp_stream_change_event.strchange_outstrms$VH;
    }
    public static short strchange_outstrms$get(MemorySegment seg) {
        return (short)sctp_stream_change_event.strchange_outstrms$VH.get(seg);
    }
    public static void strchange_outstrms$set( MemorySegment seg, short x) {
        sctp_stream_change_event.strchange_outstrms$VH.set(seg, x);
    }
    public static short strchange_outstrms$get(MemorySegment seg, long index) {
        return (short)sctp_stream_change_event.strchange_outstrms$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strchange_outstrms$set(MemorySegment seg, long index, short x) {
        sctp_stream_change_event.strchange_outstrms$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


