// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_sndinfo {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("snd_sid"),
        Constants$root.C_SHORT$LAYOUT.withName("snd_flags"),
        Constants$root.C_INT$LAYOUT.withName("snd_ppid"),
        Constants$root.C_INT$LAYOUT.withName("snd_context"),
        Constants$root.C_INT$LAYOUT.withName("snd_assoc_id")
    ).withName("sctp_sndinfo");
    public static MemoryLayout $LAYOUT() {
        return sctp_sndinfo.$struct$LAYOUT;
    }
    static final VarHandle snd_sid$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("snd_sid"));
    public static VarHandle snd_sid$VH() {
        return sctp_sndinfo.snd_sid$VH;
    }
    public static short snd_sid$get(MemorySegment seg) {
        return (short)sctp_sndinfo.snd_sid$VH.get(seg);
    }
    public static void snd_sid$set( MemorySegment seg, short x) {
        sctp_sndinfo.snd_sid$VH.set(seg, x);
    }
    public static short snd_sid$get(MemorySegment seg, long index) {
        return (short)sctp_sndinfo.snd_sid$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void snd_sid$set(MemorySegment seg, long index, short x) {
        sctp_sndinfo.snd_sid$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle snd_flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("snd_flags"));
    public static VarHandle snd_flags$VH() {
        return sctp_sndinfo.snd_flags$VH;
    }
    public static short snd_flags$get(MemorySegment seg) {
        return (short)sctp_sndinfo.snd_flags$VH.get(seg);
    }
    public static void snd_flags$set( MemorySegment seg, short x) {
        sctp_sndinfo.snd_flags$VH.set(seg, x);
    }
    public static short snd_flags$get(MemorySegment seg, long index) {
        return (short)sctp_sndinfo.snd_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void snd_flags$set(MemorySegment seg, long index, short x) {
        sctp_sndinfo.snd_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle snd_ppid$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("snd_ppid"));
    public static VarHandle snd_ppid$VH() {
        return sctp_sndinfo.snd_ppid$VH;
    }
    public static int snd_ppid$get(MemorySegment seg) {
        return (int)sctp_sndinfo.snd_ppid$VH.get(seg);
    }
    public static void snd_ppid$set( MemorySegment seg, int x) {
        sctp_sndinfo.snd_ppid$VH.set(seg, x);
    }
    public static int snd_ppid$get(MemorySegment seg, long index) {
        return (int)sctp_sndinfo.snd_ppid$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void snd_ppid$set(MemorySegment seg, long index, int x) {
        sctp_sndinfo.snd_ppid$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle snd_context$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("snd_context"));
    public static VarHandle snd_context$VH() {
        return sctp_sndinfo.snd_context$VH;
    }
    public static int snd_context$get(MemorySegment seg) {
        return (int)sctp_sndinfo.snd_context$VH.get(seg);
    }
    public static void snd_context$set( MemorySegment seg, int x) {
        sctp_sndinfo.snd_context$VH.set(seg, x);
    }
    public static int snd_context$get(MemorySegment seg, long index) {
        return (int)sctp_sndinfo.snd_context$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void snd_context$set(MemorySegment seg, long index, int x) {
        sctp_sndinfo.snd_context$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle snd_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("snd_assoc_id"));
    public static VarHandle snd_assoc_id$VH() {
        return sctp_sndinfo.snd_assoc_id$VH;
    }
    public static int snd_assoc_id$get(MemorySegment seg) {
        return (int)sctp_sndinfo.snd_assoc_id$VH.get(seg);
    }
    public static void snd_assoc_id$set( MemorySegment seg, int x) {
        sctp_sndinfo.snd_assoc_id$VH.set(seg, x);
    }
    public static int snd_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_sndinfo.snd_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void snd_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_sndinfo.snd_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


