// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_sendv_spa {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("sendv_flags"),
        MemoryLayout.structLayout(
            Constants$root.C_SHORT$LAYOUT.withName("snd_sid"),
            Constants$root.C_SHORT$LAYOUT.withName("snd_flags"),
            Constants$root.C_INT$LAYOUT.withName("snd_ppid"),
            Constants$root.C_INT$LAYOUT.withName("snd_context"),
            Constants$root.C_INT$LAYOUT.withName("snd_assoc_id")
        ).withName("sendv_sndinfo")
    ).withName("sctp_sendv_spa");
    public static MemoryLayout $LAYOUT() {
        return sctp_sendv_spa.$struct$LAYOUT;
    }
    static final VarHandle sendv_flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sendv_flags"));
    public static VarHandle sendv_flags$VH() {
        return sctp_sendv_spa.sendv_flags$VH;
    }
    public static int sendv_flags$get(MemorySegment seg) {
        return (int)sctp_sendv_spa.sendv_flags$VH.get(seg);
    }
    public static void sendv_flags$set( MemorySegment seg, int x) {
        sctp_sendv_spa.sendv_flags$VH.set(seg, x);
    }
    public static int sendv_flags$get(MemorySegment seg, long index) {
        return (int)sctp_sendv_spa.sendv_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sendv_flags$set(MemorySegment seg, long index, int x) {
        sctp_sendv_spa.sendv_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment sendv_sndinfo$slice(MemorySegment seg) {
        return seg.asSlice(4, 16);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


