// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_authkey_event {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("auth_type"),
        Constants$root.C_SHORT$LAYOUT.withName("auth_flags"),
        Constants$root.C_INT$LAYOUT.withName("auth_length"),
        Constants$root.C_SHORT$LAYOUT.withName("auth_keynumber"),
        Constants$root.C_SHORT$LAYOUT.withName("auth_altkeynumber"),
        Constants$root.C_INT$LAYOUT.withName("auth_indication"),
        Constants$root.C_INT$LAYOUT.withName("auth_assoc_id")
    ).withName("sctp_authkey_event");
    public static MemoryLayout $LAYOUT() {
        return sctp_authkey_event.$struct$LAYOUT;
    }
    static final VarHandle auth_type$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("auth_type"));
    public static VarHandle auth_type$VH() {
        return sctp_authkey_event.auth_type$VH;
    }
    public static short auth_type$get(MemorySegment seg) {
        return (short)sctp_authkey_event.auth_type$VH.get(seg);
    }
    public static void auth_type$set( MemorySegment seg, short x) {
        sctp_authkey_event.auth_type$VH.set(seg, x);
    }
    public static short auth_type$get(MemorySegment seg, long index) {
        return (short)sctp_authkey_event.auth_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void auth_type$set(MemorySegment seg, long index, short x) {
        sctp_authkey_event.auth_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle auth_flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("auth_flags"));
    public static VarHandle auth_flags$VH() {
        return sctp_authkey_event.auth_flags$VH;
    }
    public static short auth_flags$get(MemorySegment seg) {
        return (short)sctp_authkey_event.auth_flags$VH.get(seg);
    }
    public static void auth_flags$set( MemorySegment seg, short x) {
        sctp_authkey_event.auth_flags$VH.set(seg, x);
    }
    public static short auth_flags$get(MemorySegment seg, long index) {
        return (short)sctp_authkey_event.auth_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void auth_flags$set(MemorySegment seg, long index, short x) {
        sctp_authkey_event.auth_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle auth_length$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("auth_length"));
    public static VarHandle auth_length$VH() {
        return sctp_authkey_event.auth_length$VH;
    }
    public static int auth_length$get(MemorySegment seg) {
        return (int)sctp_authkey_event.auth_length$VH.get(seg);
    }
    public static void auth_length$set( MemorySegment seg, int x) {
        sctp_authkey_event.auth_length$VH.set(seg, x);
    }
    public static int auth_length$get(MemorySegment seg, long index) {
        return (int)sctp_authkey_event.auth_length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void auth_length$set(MemorySegment seg, long index, int x) {
        sctp_authkey_event.auth_length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle auth_keynumber$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("auth_keynumber"));
    public static VarHandle auth_keynumber$VH() {
        return sctp_authkey_event.auth_keynumber$VH;
    }
    public static short auth_keynumber$get(MemorySegment seg) {
        return (short)sctp_authkey_event.auth_keynumber$VH.get(seg);
    }
    public static void auth_keynumber$set( MemorySegment seg, short x) {
        sctp_authkey_event.auth_keynumber$VH.set(seg, x);
    }
    public static short auth_keynumber$get(MemorySegment seg, long index) {
        return (short)sctp_authkey_event.auth_keynumber$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void auth_keynumber$set(MemorySegment seg, long index, short x) {
        sctp_authkey_event.auth_keynumber$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle auth_altkeynumber$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("auth_altkeynumber"));
    public static VarHandle auth_altkeynumber$VH() {
        return sctp_authkey_event.auth_altkeynumber$VH;
    }
    public static short auth_altkeynumber$get(MemorySegment seg) {
        return (short)sctp_authkey_event.auth_altkeynumber$VH.get(seg);
    }
    public static void auth_altkeynumber$set( MemorySegment seg, short x) {
        sctp_authkey_event.auth_altkeynumber$VH.set(seg, x);
    }
    public static short auth_altkeynumber$get(MemorySegment seg, long index) {
        return (short)sctp_authkey_event.auth_altkeynumber$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void auth_altkeynumber$set(MemorySegment seg, long index, short x) {
        sctp_authkey_event.auth_altkeynumber$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle auth_indication$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("auth_indication"));
    public static VarHandle auth_indication$VH() {
        return sctp_authkey_event.auth_indication$VH;
    }
    public static int auth_indication$get(MemorySegment seg) {
        return (int)sctp_authkey_event.auth_indication$VH.get(seg);
    }
    public static void auth_indication$set( MemorySegment seg, int x) {
        sctp_authkey_event.auth_indication$VH.set(seg, x);
    }
    public static int auth_indication$get(MemorySegment seg, long index) {
        return (int)sctp_authkey_event.auth_indication$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void auth_indication$set(MemorySegment seg, long index, int x) {
        sctp_authkey_event.auth_indication$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle auth_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("auth_assoc_id"));
    public static VarHandle auth_assoc_id$VH() {
        return sctp_authkey_event.auth_assoc_id$VH;
    }
    public static int auth_assoc_id$get(MemorySegment seg) {
        return (int)sctp_authkey_event.auth_assoc_id$VH.get(seg);
    }
    public static void auth_assoc_id$set( MemorySegment seg, int x) {
        sctp_authkey_event.auth_assoc_id$VH.set(seg, x);
    }
    public static int auth_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_authkey_event.auth_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void auth_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_authkey_event.auth_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


