// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_authkey {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("sca_assoc_id"),
        Constants$root.C_SHORT$LAYOUT.withName("sca_keynumber"),
        Constants$root.C_SHORT$LAYOUT.withName("sca_keylength"),
        MemoryLayout.sequenceLayout(Constants$root.C_CHAR$LAYOUT).withName("sca_key")
    ).withName("sctp_authkey");
    public static MemoryLayout $LAYOUT() {
        return sctp_authkey.$struct$LAYOUT;
    }
    static final VarHandle sca_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sca_assoc_id"));
    public static VarHandle sca_assoc_id$VH() {
        return sctp_authkey.sca_assoc_id$VH;
    }
    public static int sca_assoc_id$get(MemorySegment seg) {
        return (int)sctp_authkey.sca_assoc_id$VH.get(seg);
    }
    public static void sca_assoc_id$set( MemorySegment seg, int x) {
        sctp_authkey.sca_assoc_id$VH.set(seg, x);
    }
    public static int sca_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_authkey.sca_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sca_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_authkey.sca_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sca_keynumber$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sca_keynumber"));
    public static VarHandle sca_keynumber$VH() {
        return sctp_authkey.sca_keynumber$VH;
    }
    public static short sca_keynumber$get(MemorySegment seg) {
        return (short)sctp_authkey.sca_keynumber$VH.get(seg);
    }
    public static void sca_keynumber$set( MemorySegment seg, short x) {
        sctp_authkey.sca_keynumber$VH.set(seg, x);
    }
    public static short sca_keynumber$get(MemorySegment seg, long index) {
        return (short)sctp_authkey.sca_keynumber$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sca_keynumber$set(MemorySegment seg, long index, short x) {
        sctp_authkey.sca_keynumber$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sca_keylength$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sca_keylength"));
    public static VarHandle sca_keylength$VH() {
        return sctp_authkey.sca_keylength$VH;
    }
    public static short sca_keylength$get(MemorySegment seg) {
        return (short)sctp_authkey.sca_keylength$VH.get(seg);
    }
    public static void sca_keylength$set( MemorySegment seg, short x) {
        sctp_authkey.sca_keylength$VH.set(seg, x);
    }
    public static short sca_keylength$get(MemorySegment seg, long index) {
        return (short)sctp_authkey.sca_keylength$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sca_keylength$set(MemorySegment seg, long index, short x) {
        sctp_authkey.sca_keylength$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


