// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_paddrinfo {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("spinfo_assoc_id"),
        MemoryLayout.structLayout(
            Constants$root.C_SHORT$LAYOUT.withName("ss_family"),
            MemoryLayout.sequenceLayout(118, Constants$root.C_CHAR$LAYOUT).withName("__ss_padding"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("__ss_align")
        ).withName("spinfo_address"),
        Constants$root.C_INT$LAYOUT.withName("spinfo_state"),
        Constants$root.C_INT$LAYOUT.withName("spinfo_cwnd"),
        Constants$root.C_INT$LAYOUT.withName("spinfo_srtt"),
        Constants$root.C_INT$LAYOUT.withName("spinfo_rto"),
        Constants$root.C_INT$LAYOUT.withName("spinfo_mtu")
    ).withName("sctp_paddrinfo");
    public static MemoryLayout $LAYOUT() {
        return sctp_paddrinfo.$struct$LAYOUT;
    }
    static final VarHandle spinfo_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("spinfo_assoc_id"));
    public static VarHandle spinfo_assoc_id$VH() {
        return sctp_paddrinfo.spinfo_assoc_id$VH;
    }
    public static int spinfo_assoc_id$get(MemorySegment seg) {
        return (int)sctp_paddrinfo.spinfo_assoc_id$VH.get(seg);
    }
    public static void spinfo_assoc_id$set( MemorySegment seg, int x) {
        sctp_paddrinfo.spinfo_assoc_id$VH.set(seg, x);
    }
    public static int spinfo_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_paddrinfo.spinfo_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void spinfo_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_paddrinfo.spinfo_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment spinfo_address$slice(MemorySegment seg) {
        return seg.asSlice(4, 128);
    }
    static final VarHandle spinfo_state$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("spinfo_state"));
    public static VarHandle spinfo_state$VH() {
        return sctp_paddrinfo.spinfo_state$VH;
    }
    public static int spinfo_state$get(MemorySegment seg) {
        return (int)sctp_paddrinfo.spinfo_state$VH.get(seg);
    }
    public static void spinfo_state$set( MemorySegment seg, int x) {
        sctp_paddrinfo.spinfo_state$VH.set(seg, x);
    }
    public static int spinfo_state$get(MemorySegment seg, long index) {
        return (int)sctp_paddrinfo.spinfo_state$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void spinfo_state$set(MemorySegment seg, long index, int x) {
        sctp_paddrinfo.spinfo_state$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle spinfo_cwnd$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("spinfo_cwnd"));
    public static VarHandle spinfo_cwnd$VH() {
        return sctp_paddrinfo.spinfo_cwnd$VH;
    }
    public static int spinfo_cwnd$get(MemorySegment seg) {
        return (int)sctp_paddrinfo.spinfo_cwnd$VH.get(seg);
    }
    public static void spinfo_cwnd$set( MemorySegment seg, int x) {
        sctp_paddrinfo.spinfo_cwnd$VH.set(seg, x);
    }
    public static int spinfo_cwnd$get(MemorySegment seg, long index) {
        return (int)sctp_paddrinfo.spinfo_cwnd$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void spinfo_cwnd$set(MemorySegment seg, long index, int x) {
        sctp_paddrinfo.spinfo_cwnd$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle spinfo_srtt$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("spinfo_srtt"));
    public static VarHandle spinfo_srtt$VH() {
        return sctp_paddrinfo.spinfo_srtt$VH;
    }
    public static int spinfo_srtt$get(MemorySegment seg) {
        return (int)sctp_paddrinfo.spinfo_srtt$VH.get(seg);
    }
    public static void spinfo_srtt$set( MemorySegment seg, int x) {
        sctp_paddrinfo.spinfo_srtt$VH.set(seg, x);
    }
    public static int spinfo_srtt$get(MemorySegment seg, long index) {
        return (int)sctp_paddrinfo.spinfo_srtt$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void spinfo_srtt$set(MemorySegment seg, long index, int x) {
        sctp_paddrinfo.spinfo_srtt$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle spinfo_rto$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("spinfo_rto"));
    public static VarHandle spinfo_rto$VH() {
        return sctp_paddrinfo.spinfo_rto$VH;
    }
    public static int spinfo_rto$get(MemorySegment seg) {
        return (int)sctp_paddrinfo.spinfo_rto$VH.get(seg);
    }
    public static void spinfo_rto$set( MemorySegment seg, int x) {
        sctp_paddrinfo.spinfo_rto$VH.set(seg, x);
    }
    public static int spinfo_rto$get(MemorySegment seg, long index) {
        return (int)sctp_paddrinfo.spinfo_rto$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void spinfo_rto$set(MemorySegment seg, long index, int x) {
        sctp_paddrinfo.spinfo_rto$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle spinfo_mtu$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("spinfo_mtu"));
    public static VarHandle spinfo_mtu$VH() {
        return sctp_paddrinfo.spinfo_mtu$VH;
    }
    public static int spinfo_mtu$get(MemorySegment seg) {
        return (int)sctp_paddrinfo.spinfo_mtu$VH.get(seg);
    }
    public static void spinfo_mtu$set( MemorySegment seg, int x) {
        sctp_paddrinfo.spinfo_mtu$VH.set(seg, x);
    }
    public static int spinfo_mtu$get(MemorySegment seg, long index) {
        return (int)sctp_paddrinfo.spinfo_mtu$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void spinfo_mtu$set(MemorySegment seg, long index, int x) {
        sctp_paddrinfo.spinfo_mtu$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


