// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_shutdown_event {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("sse_type"),
        Constants$root.C_SHORT$LAYOUT.withName("sse_flags"),
        Constants$root.C_INT$LAYOUT.withName("sse_length"),
        Constants$root.C_INT$LAYOUT.withName("sse_assoc_id")
    ).withName("sctp_shutdown_event");
    public static MemoryLayout $LAYOUT() {
        return sctp_shutdown_event.$struct$LAYOUT;
    }
    static final VarHandle sse_type$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sse_type"));
    public static VarHandle sse_type$VH() {
        return sctp_shutdown_event.sse_type$VH;
    }
    public static short sse_type$get(MemorySegment seg) {
        return (short)sctp_shutdown_event.sse_type$VH.get(seg);
    }
    public static void sse_type$set( MemorySegment seg, short x) {
        sctp_shutdown_event.sse_type$VH.set(seg, x);
    }
    public static short sse_type$get(MemorySegment seg, long index) {
        return (short)sctp_shutdown_event.sse_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sse_type$set(MemorySegment seg, long index, short x) {
        sctp_shutdown_event.sse_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sse_flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sse_flags"));
    public static VarHandle sse_flags$VH() {
        return sctp_shutdown_event.sse_flags$VH;
    }
    public static short sse_flags$get(MemorySegment seg) {
        return (short)sctp_shutdown_event.sse_flags$VH.get(seg);
    }
    public static void sse_flags$set( MemorySegment seg, short x) {
        sctp_shutdown_event.sse_flags$VH.set(seg, x);
    }
    public static short sse_flags$get(MemorySegment seg, long index) {
        return (short)sctp_shutdown_event.sse_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sse_flags$set(MemorySegment seg, long index, short x) {
        sctp_shutdown_event.sse_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sse_length$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sse_length"));
    public static VarHandle sse_length$VH() {
        return sctp_shutdown_event.sse_length$VH;
    }
    public static int sse_length$get(MemorySegment seg) {
        return (int)sctp_shutdown_event.sse_length$VH.get(seg);
    }
    public static void sse_length$set( MemorySegment seg, int x) {
        sctp_shutdown_event.sse_length$VH.set(seg, x);
    }
    public static int sse_length$get(MemorySegment seg, long index) {
        return (int)sctp_shutdown_event.sse_length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sse_length$set(MemorySegment seg, long index, int x) {
        sctp_shutdown_event.sse_length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sse_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sse_assoc_id"));
    public static VarHandle sse_assoc_id$VH() {
        return sctp_shutdown_event.sse_assoc_id$VH;
    }
    public static int sse_assoc_id$get(MemorySegment seg) {
        return (int)sctp_shutdown_event.sse_assoc_id$VH.get(seg);
    }
    public static void sse_assoc_id$set( MemorySegment seg, int x) {
        sctp_shutdown_event.sse_assoc_id$VH.set(seg, x);
    }
    public static int sse_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_shutdown_event.sse_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sse_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_shutdown_event.sse_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


