// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_reset_streams {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("srs_assoc_id"),
        Constants$root.C_SHORT$LAYOUT.withName("srs_flags"),
        Constants$root.C_SHORT$LAYOUT.withName("srs_number_streams"),
        MemoryLayout.sequenceLayout(Constants$root.C_SHORT$LAYOUT).withName("srs_stream_list")
    ).withName("sctp_reset_streams");
    public static MemoryLayout $LAYOUT() {
        return sctp_reset_streams.$struct$LAYOUT;
    }
    static final VarHandle srs_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("srs_assoc_id"));
    public static VarHandle srs_assoc_id$VH() {
        return sctp_reset_streams.srs_assoc_id$VH;
    }
    public static int srs_assoc_id$get(MemorySegment seg) {
        return (int)sctp_reset_streams.srs_assoc_id$VH.get(seg);
    }
    public static void srs_assoc_id$set( MemorySegment seg, int x) {
        sctp_reset_streams.srs_assoc_id$VH.set(seg, x);
    }
    public static int srs_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_reset_streams.srs_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void srs_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_reset_streams.srs_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle srs_flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("srs_flags"));
    public static VarHandle srs_flags$VH() {
        return sctp_reset_streams.srs_flags$VH;
    }
    public static short srs_flags$get(MemorySegment seg) {
        return (short)sctp_reset_streams.srs_flags$VH.get(seg);
    }
    public static void srs_flags$set( MemorySegment seg, short x) {
        sctp_reset_streams.srs_flags$VH.set(seg, x);
    }
    public static short srs_flags$get(MemorySegment seg, long index) {
        return (short)sctp_reset_streams.srs_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void srs_flags$set(MemorySegment seg, long index, short x) {
        sctp_reset_streams.srs_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle srs_number_streams$VH = $struct$LAYOUT.varHandle(
            PathElement.groupElement("srs_number_streams"));
    public static VarHandle srs_number_streams$VH() {
        return sctp_reset_streams.srs_number_streams$VH;
    }
    public static short srs_number_streams$get(MemorySegment seg) {
        return (short)sctp_reset_streams.srs_number_streams$VH.get(seg);
    }
    public static void srs_number_streams$set( MemorySegment seg, short x) {
        sctp_reset_streams.srs_number_streams$VH.set(seg, x);
    }
    public static short srs_number_streams$get(MemorySegment seg, long index) {
        return (short)sctp_reset_streams.srs_number_streams$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void srs_number_streams$set(MemorySegment seg, long index, short x) {
        sctp_reset_streams.srs_number_streams$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


