// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_authinfo {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("auth_keynumber")
    ).withName("sctp_authinfo");
    public static MemoryLayout $LAYOUT() {
        return sctp_authinfo.$struct$LAYOUT;
    }
    static final VarHandle auth_keynumber$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("auth_keynumber"));
    public static VarHandle auth_keynumber$VH() {
        return sctp_authinfo.auth_keynumber$VH;
    }
    public static short auth_keynumber$get(MemorySegment seg) {
        return (short)sctp_authinfo.auth_keynumber$VH.get(seg);
    }
    public static void auth_keynumber$set( MemorySegment seg, short x) {
        sctp_authinfo.auth_keynumber$VH.set(seg, x);
    }
    public static short auth_keynumber$get(MemorySegment seg, long index) {
        return (short)sctp_authinfo.auth_keynumber$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void auth_keynumber$set(MemorySegment seg, long index, short x) {
        sctp_authinfo.auth_keynumber$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


