// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_setadaptation {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("ssb_adaptation_ind")
    ).withName("sctp_setadaptation");
    public static MemoryLayout $LAYOUT() {
        return sctp_setadaptation.$struct$LAYOUT;
    }
    static final VarHandle ssb_adaptation_ind$VH = $struct$LAYOUT.varHandle(
            PathElement.groupElement("ssb_adaptation_ind"));
    public static VarHandle ssb_adaptation_ind$VH() {
        return sctp_setadaptation.ssb_adaptation_ind$VH;
    }
    public static int ssb_adaptation_ind$get(MemorySegment seg) {
        return (int)sctp_setadaptation.ssb_adaptation_ind$VH.get(seg);
    }
    public static void ssb_adaptation_ind$set( MemorySegment seg, int x) {
        sctp_setadaptation.ssb_adaptation_ind$VH.set(seg, x);
    }
    public static int ssb_adaptation_ind$get(MemorySegment seg, long index) {
        return (int)sctp_setadaptation.ssb_adaptation_ind$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ssb_adaptation_ind$set(MemorySegment seg, long index, int x) {
        sctp_setadaptation.ssb_adaptation_ind$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


