// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_authchunk {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_CHAR$LAYOUT.withName("sauth_chunk")
    ).withName("sctp_authchunk");
    public static MemoryLayout $LAYOUT() {
        return sctp_authchunk.$struct$LAYOUT;
    }
    static final VarHandle sauth_chunk$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sauth_chunk"));
    public static VarHandle sauth_chunk$VH() {
        return sctp_authchunk.sauth_chunk$VH;
    }
    public static byte sauth_chunk$get(MemorySegment seg) {
        return (byte)sctp_authchunk.sauth_chunk$VH.get(seg);
    }
    public static void sauth_chunk$set( MemorySegment seg, byte x) {
        sctp_authchunk.sauth_chunk$VH.set(seg, x);
    }
    public static byte sauth_chunk$get(MemorySegment seg, long index) {
        return (byte)sctp_authchunk.sauth_chunk$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sauth_chunk$set(MemorySegment seg, long index, byte x) {
        sctp_authchunk.sauth_chunk$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


