// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_setpeerprim {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("sspp_assoc_id"),
        MemoryLayout.structLayout(
            Constants$root.C_SHORT$LAYOUT.withName("ss_family"),
            MemoryLayout.sequenceLayout(118, Constants$root.C_CHAR$LAYOUT).withName("__ss_padding"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("__ss_align")
        ).withName("sspp_addr")
    ).withName("sctp_setpeerprim");
    public static MemoryLayout $LAYOUT() {
        return sctp_setpeerprim.$struct$LAYOUT;
    }
    static final VarHandle sspp_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sspp_assoc_id"));
    public static VarHandle sspp_assoc_id$VH() {
        return sctp_setpeerprim.sspp_assoc_id$VH;
    }
    public static int sspp_assoc_id$get(MemorySegment seg) {
        return (int)sctp_setpeerprim.sspp_assoc_id$VH.get(seg);
    }
    public static void sspp_assoc_id$set( MemorySegment seg, int x) {
        sctp_setpeerprim.sspp_assoc_id$VH.set(seg, x);
    }
    public static int sspp_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_setpeerprim.sspp_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sspp_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_setpeerprim.sspp_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment sspp_addr$slice(MemorySegment seg) {
        return seg.asSlice(4, 128);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


