// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_assoc_value {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("assoc_id"),
        Constants$root.C_INT$LAYOUT.withName("assoc_value")
    ).withName("sctp_assoc_value");
    public static MemoryLayout $LAYOUT() {
        return sctp_assoc_value.$struct$LAYOUT;
    }
    static final VarHandle assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("assoc_id"));
    public static VarHandle assoc_id$VH() {
        return sctp_assoc_value.assoc_id$VH;
    }
    public static int assoc_id$get(MemorySegment seg) {
        return (int)sctp_assoc_value.assoc_id$VH.get(seg);
    }
    public static void assoc_id$set( MemorySegment seg, int x) {
        sctp_assoc_value.assoc_id$VH.set(seg, x);
    }
    public static int assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_assoc_value.assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_assoc_value.assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle assoc_value$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("assoc_value"));
    public static VarHandle assoc_value$VH() {
        return sctp_assoc_value.assoc_value$VH;
    }
    public static int assoc_value$get(MemorySegment seg) {
        return (int)sctp_assoc_value.assoc_value$VH.get(seg);
    }
    public static void assoc_value$set( MemorySegment seg, int x) {
        sctp_assoc_value.assoc_value$VH.set(seg, x);
    }
    public static int assoc_value$get(MemorySegment seg, long index) {
        return (int)sctp_assoc_value.assoc_value$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void assoc_value$set(MemorySegment seg, long index, int x) {
        sctp_assoc_value.assoc_value$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


