// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_authchunks {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("gauth_assoc_id"),
        Constants$root.C_INT$LAYOUT.withName("gauth_number_of_chunks"),
        MemoryLayout.sequenceLayout(Constants$root.C_CHAR$LAYOUT).withName("gauth_chunks")
    ).withName("sctp_authchunks");
    public static MemoryLayout $LAYOUT() {
        return sctp_authchunks.$struct$LAYOUT;
    }
    static final VarHandle gauth_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("gauth_assoc_id"));
    public static VarHandle gauth_assoc_id$VH() {
        return sctp_authchunks.gauth_assoc_id$VH;
    }
    public static int gauth_assoc_id$get(MemorySegment seg) {
        return (int)sctp_authchunks.gauth_assoc_id$VH.get(seg);
    }
    public static void gauth_assoc_id$set( MemorySegment seg, int x) {
        sctp_authchunks.gauth_assoc_id$VH.set(seg, x);
    }
    public static int gauth_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_authchunks.gauth_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void gauth_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_authchunks.gauth_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle gauth_number_of_chunks$VH = $struct$LAYOUT.varHandle(
            PathElement.groupElement("gauth_number_of_chunks"));
    public static VarHandle gauth_number_of_chunks$VH() {
        return sctp_authchunks.gauth_number_of_chunks$VH;
    }
    public static int gauth_number_of_chunks$get(MemorySegment seg) {
        return (int)sctp_authchunks.gauth_number_of_chunks$VH.get(seg);
    }
    public static void gauth_number_of_chunks$set( MemorySegment seg, int x) {
        sctp_authchunks.gauth_number_of_chunks$VH.set(seg, x);
    }
    public static int gauth_number_of_chunks$get(MemorySegment seg, long index) {
        return (int)sctp_authchunks.gauth_number_of_chunks$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void gauth_number_of_chunks$set(MemorySegment seg, long index, int x) {
        sctp_authchunks.gauth_number_of_chunks$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


