// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_authkeyid {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("scact_assoc_id"),
        Constants$root.C_SHORT$LAYOUT.withName("scact_keynumber"),
        MemoryLayout.paddingLayout(16)
    ).withName("sctp_authkeyid");
    public static MemoryLayout $LAYOUT() {
        return sctp_authkeyid.$struct$LAYOUT;
    }
    static final VarHandle scact_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("scact_assoc_id"));
    public static VarHandle scact_assoc_id$VH() {
        return sctp_authkeyid.scact_assoc_id$VH;
    }
    public static int scact_assoc_id$get(MemorySegment seg) {
        return (int)sctp_authkeyid.scact_assoc_id$VH.get(seg);
    }
    public static void scact_assoc_id$set( MemorySegment seg, int x) {
        sctp_authkeyid.scact_assoc_id$VH.set(seg, x);
    }
    public static int scact_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_authkeyid.scact_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void scact_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_authkeyid.scact_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle scact_keynumber$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("scact_keynumber"));
    public static VarHandle scact_keynumber$VH() {
        return sctp_authkeyid.scact_keynumber$VH;
    }
    public static short scact_keynumber$get(MemorySegment seg) {
        return (short)sctp_authkeyid.scact_keynumber$VH.get(seg);
    }
    public static void scact_keynumber$set( MemorySegment seg, short x) {
        sctp_authkeyid.scact_keynumber$VH.set(seg, x);
    }
    public static short scact_keynumber$get(MemorySegment seg, long index) {
        return (short)sctp_authkeyid.scact_keynumber$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void scact_keynumber$set(MemorySegment seg, long index, short x) {
        sctp_authkeyid.scact_keynumber$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


