// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_add_streams {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("sas_assoc_id"),
        Constants$root.C_SHORT$LAYOUT.withName("sas_instrms"),
        Constants$root.C_SHORT$LAYOUT.withName("sas_outstrms")
    ).withName("sctp_add_streams");
    public static MemoryLayout $LAYOUT() {
        return sctp_add_streams.$struct$LAYOUT;
    }
    static final VarHandle sas_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sas_assoc_id"));
    public static VarHandle sas_assoc_id$VH() {
        return sctp_add_streams.sas_assoc_id$VH;
    }
    public static int sas_assoc_id$get(MemorySegment seg) {
        return (int)sctp_add_streams.sas_assoc_id$VH.get(seg);
    }
    public static void sas_assoc_id$set( MemorySegment seg, int x) {
        sctp_add_streams.sas_assoc_id$VH.set(seg, x);
    }
    public static int sas_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_add_streams.sas_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sas_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_add_streams.sas_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sas_instrms$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sas_instrms"));
    public static VarHandle sas_instrms$VH() {
        return sctp_add_streams.sas_instrms$VH;
    }
    public static short sas_instrms$get(MemorySegment seg) {
        return (short)sctp_add_streams.sas_instrms$VH.get(seg);
    }
    public static void sas_instrms$set( MemorySegment seg, short x) {
        sctp_add_streams.sas_instrms$VH.set(seg, x);
    }
    public static short sas_instrms$get(MemorySegment seg, long index) {
        return (short)sctp_add_streams.sas_instrms$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sas_instrms$set(MemorySegment seg, long index, short x) {
        sctp_add_streams.sas_instrms$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sas_outstrms$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sas_outstrms"));
    public static VarHandle sas_outstrms$VH() {
        return sctp_add_streams.sas_outstrms$VH;
    }
    public static short sas_outstrms$get(MemorySegment seg) {
        return (short)sctp_add_streams.sas_outstrms$VH.get(seg);
    }
    public static void sas_outstrms$set( MemorySegment seg, short x) {
        sctp_add_streams.sas_outstrms$VH.set(seg, x);
    }
    public static short sas_outstrms$get(MemorySegment seg, long index) {
        return (short)sctp_add_streams.sas_outstrms$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sas_outstrms$set(MemorySegment seg, long index, short x) {
        sctp_add_streams.sas_outstrms$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


