// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_remote_error {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("sre_type"),
        Constants$root.C_SHORT$LAYOUT.withName("sre_flags"),
        Constants$root.C_INT$LAYOUT.withName("sre_length"),
        Constants$root.C_SHORT$LAYOUT.withName("sre_error"),
        MemoryLayout.paddingLayout(16),
        Constants$root.C_INT$LAYOUT.withName("sre_assoc_id"),
        MemoryLayout.sequenceLayout(0, Constants$root.C_CHAR$LAYOUT).withName("sre_data")
    ).withName("sctp_remote_error");
    public static MemoryLayout $LAYOUT() {
        return sctp_remote_error.$struct$LAYOUT;
    }
    static final VarHandle sre_type$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sre_type"));
    public static VarHandle sre_type$VH() {
        return sctp_remote_error.sre_type$VH;
    }
    public static short sre_type$get(MemorySegment seg) {
        return (short)sctp_remote_error.sre_type$VH.get(seg);
    }
    public static void sre_type$set( MemorySegment seg, short x) {
        sctp_remote_error.sre_type$VH.set(seg, x);
    }
    public static short sre_type$get(MemorySegment seg, long index) {
        return (short)sctp_remote_error.sre_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sre_type$set(MemorySegment seg, long index, short x) {
        sctp_remote_error.sre_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sre_flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sre_flags"));
    public static VarHandle sre_flags$VH() {
        return sctp_remote_error.sre_flags$VH;
    }
    public static short sre_flags$get(MemorySegment seg) {
        return (short)sctp_remote_error.sre_flags$VH.get(seg);
    }
    public static void sre_flags$set( MemorySegment seg, short x) {
        sctp_remote_error.sre_flags$VH.set(seg, x);
    }
    public static short sre_flags$get(MemorySegment seg, long index) {
        return (short)sctp_remote_error.sre_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sre_flags$set(MemorySegment seg, long index, short x) {
        sctp_remote_error.sre_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sre_length$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sre_length"));
    public static VarHandle sre_length$VH() {
        return sctp_remote_error.sre_length$VH;
    }
    public static int sre_length$get(MemorySegment seg) {
        return (int)sctp_remote_error.sre_length$VH.get(seg);
    }
    public static void sre_length$set( MemorySegment seg, int x) {
        sctp_remote_error.sre_length$VH.set(seg, x);
    }
    public static int sre_length$get(MemorySegment seg, long index) {
        return (int)sctp_remote_error.sre_length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sre_length$set(MemorySegment seg, long index, int x) {
        sctp_remote_error.sre_length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sre_error$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sre_error"));
    public static VarHandle sre_error$VH() {
        return sctp_remote_error.sre_error$VH;
    }
    public static short sre_error$get(MemorySegment seg) {
        return (short)sctp_remote_error.sre_error$VH.get(seg);
    }
    public static void sre_error$set( MemorySegment seg, short x) {
        sctp_remote_error.sre_error$VH.set(seg, x);
    }
    public static short sre_error$get(MemorySegment seg, long index) {
        return (short)sctp_remote_error.sre_error$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sre_error$set(MemorySegment seg, long index, short x) {
        sctp_remote_error.sre_error$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sre_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("sre_assoc_id"));
    public static VarHandle sre_assoc_id$VH() {
        return sctp_remote_error.sre_assoc_id$VH;
    }
    public static int sre_assoc_id$get(MemorySegment seg) {
        return (int)sctp_remote_error.sre_assoc_id$VH.get(seg);
    }
    public static void sre_assoc_id$set( MemorySegment seg, int x) {
        sctp_remote_error.sre_assoc_id$VH.set(seg, x);
    }
    public static int sre_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_remote_error.sre_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sre_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_remote_error.sre_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment sre_data$slice(MemorySegment seg) {
        return seg.asSlice(16, 0);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


