// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_stream_reset_event {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("strreset_type"),
        Constants$root.C_SHORT$LAYOUT.withName("strreset_flags"),
        Constants$root.C_INT$LAYOUT.withName("strreset_length"),
        Constants$root.C_INT$LAYOUT.withName("strreset_assoc_id"),
        MemoryLayout.sequenceLayout(Constants$root.C_SHORT$LAYOUT).withName("strreset_stream_list")
    ).withName("sctp_stream_reset_event");
    public static MemoryLayout $LAYOUT() {
        return sctp_stream_reset_event.$struct$LAYOUT;
    }
    static final VarHandle strreset_type$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("strreset_type"));
    public static VarHandle strreset_type$VH() {
        return sctp_stream_reset_event.strreset_type$VH;
    }
    public static short strreset_type$get(MemorySegment seg) {
        return (short)sctp_stream_reset_event.strreset_type$VH.get(seg);
    }
    public static void strreset_type$set( MemorySegment seg, short x) {
        sctp_stream_reset_event.strreset_type$VH.set(seg, x);
    }
    public static short strreset_type$get(MemorySegment seg, long index) {
        return (short)sctp_stream_reset_event.strreset_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strreset_type$set(MemorySegment seg, long index, short x) {
        sctp_stream_reset_event.strreset_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strreset_flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("strreset_flags"));
    public static VarHandle strreset_flags$VH() {
        return sctp_stream_reset_event.strreset_flags$VH;
    }
    public static short strreset_flags$get(MemorySegment seg) {
        return (short)sctp_stream_reset_event.strreset_flags$VH.get(seg);
    }
    public static void strreset_flags$set( MemorySegment seg, short x) {
        sctp_stream_reset_event.strreset_flags$VH.set(seg, x);
    }
    public static short strreset_flags$get(MemorySegment seg, long index) {
        return (short)sctp_stream_reset_event.strreset_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strreset_flags$set(MemorySegment seg, long index, short x) {
        sctp_stream_reset_event.strreset_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strreset_length$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("strreset_length"));
    public static VarHandle strreset_length$VH() {
        return sctp_stream_reset_event.strreset_length$VH;
    }
    public static int strreset_length$get(MemorySegment seg) {
        return (int)sctp_stream_reset_event.strreset_length$VH.get(seg);
    }
    public static void strreset_length$set( MemorySegment seg, int x) {
        sctp_stream_reset_event.strreset_length$VH.set(seg, x);
    }
    public static int strreset_length$get(MemorySegment seg, long index) {
        return (int)sctp_stream_reset_event.strreset_length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strreset_length$set(MemorySegment seg, long index, int x) {
        sctp_stream_reset_event.strreset_length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle strreset_assoc_id$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("strreset_assoc_id"));
    public static VarHandle strreset_assoc_id$VH() {
        return sctp_stream_reset_event.strreset_assoc_id$VH;
    }
    public static int strreset_assoc_id$get(MemorySegment seg) {
        return (int)sctp_stream_reset_event.strreset_assoc_id$VH.get(seg);
    }
    public static void strreset_assoc_id$set( MemorySegment seg, int x) {
        sctp_stream_reset_event.strreset_assoc_id$VH.set(seg, x);
    }
    public static int strreset_assoc_id$get(MemorySegment seg, long index) {
        return (int)sctp_stream_reset_event.strreset_assoc_id$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void strreset_assoc_id$set(MemorySegment seg, long index, int x) {
        sctp_stream_reset_event.strreset_assoc_id$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


