// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_peeloff_flags_arg_t {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("associd"),
            Constants$root.C_INT$LAYOUT.withName("sd")
        ).withName("p_arg"),
        Constants$root.C_INT$LAYOUT.withName("flags")
    );
    public static MemoryLayout $LAYOUT() {
        return sctp_peeloff_flags_arg_t.$struct$LAYOUT;
    }
    public static MemorySegment p_arg$slice(MemorySegment seg) {
        return seg.asSlice(0, 8);
    }
    static final VarHandle flags$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("flags"));
    public static VarHandle flags$VH() {
        return sctp_peeloff_flags_arg_t.flags$VH;
    }
    public static int flags$get(MemorySegment seg) {
        return (int)sctp_peeloff_flags_arg_t.flags$VH.get(seg);
    }
    public static void flags$set( MemorySegment seg, int x) {
        sctp_peeloff_flags_arg_t.flags$VH.set(seg, x);
    }
    public static int flags$get(MemorySegment seg, long index) {
        return (int)sctp_peeloff_flags_arg_t.flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void flags$set(MemorySegment seg, long index, int x) {
        sctp_peeloff_flags_arg_t.flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


