// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_hmacalgo {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("shmac_num_idents"),
        MemoryLayout.sequenceLayout(Constants$root.C_SHORT$LAYOUT).withName("shmac_idents")
    ).withName("sctp_hmacalgo");
    public static MemoryLayout $LAYOUT() {
        return sctp_hmacalgo.$struct$LAYOUT;
    }
    static final VarHandle shmac_num_idents$VH = $struct$LAYOUT.varHandle(PathElement.groupElement("shmac_num_idents"));
    public static VarHandle shmac_num_idents$VH() {
        return sctp_hmacalgo.shmac_num_idents$VH;
    }
    public static int shmac_num_idents$get(MemorySegment seg) {
        return (int)sctp_hmacalgo.shmac_num_idents$VH.get(seg);
    }
    public static void shmac_num_idents$set( MemorySegment seg, int x) {
        sctp_hmacalgo.shmac_num_idents$VH.set(seg, x);
    }
    public static int shmac_num_idents$get(MemorySegment seg, long index) {
        return (int)sctp_hmacalgo.shmac_num_idents$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void shmac_num_idents$set(MemorySegment seg, long index, int x) {
        sctp_hmacalgo.shmac_num_idents$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


