// Generated by jextract

package netinet.sctp;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class sctp_assoc_ids {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("gaids_number_of_ids"),
        MemoryLayout.sequenceLayout(Constants$root.C_INT$LAYOUT).withName("gaids_assoc_id")
    ).withName("sctp_assoc_ids");
    public static MemoryLayout $LAYOUT() {
        return sctp_assoc_ids.$struct$LAYOUT;
    }
    static final VarHandle gaids_number_of_ids$VH = $struct$LAYOUT.varHandle(
            PathElement.groupElement("gaids_number_of_ids"));
    public static VarHandle gaids_number_of_ids$VH() {
        return sctp_assoc_ids.gaids_number_of_ids$VH;
    }
    public static int gaids_number_of_ids$get(MemorySegment seg) {
        return (int)sctp_assoc_ids.gaids_number_of_ids$VH.get(seg);
    }
    public static void gaids_number_of_ids$set( MemorySegment seg, int x) {
        sctp_assoc_ids.gaids_number_of_ids$VH.set(seg, x);
    }
    public static int gaids_number_of_ids$get(MemorySegment seg, long index) {
        return (int)sctp_assoc_ids.gaids_number_of_ids$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void gaids_number_of_ids$set(MemorySegment seg, long index, int x) {
        sctp_assoc_ids.gaids_number_of_ids$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


